# Generated by Django 4.0 on 2022-06-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='user_follow',
        ),
    ]
